name: Submit URLs to Google Indexing API

on:
  schedule:
    - cron: '0 * * * *'  # يشغل كل ساعة (يمكنك تغييره حسب رغبتك)
  workflow_dispatch:     # لتشغيله يدوياً من GitHub متى تشاء

jobs:
  indexing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Write service account json to file
      run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service_account.json

    - name: Install dependencies
      run: pip install google-auth google-api-python-client requests

    - name: Run indexing script
      run: python indexing_script.py
