name: Submit URLs to Google Indexing API
 run: |
    python -m pip install --upgrade pip
    pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests
on:
  schedule:
    - cron: '0 * * * *'  # يشغل كل ساعة (يمكنك تغييره حسب رغبتك)
  workflow_dispatch:     # لتشغيله يدوياً من GitHub متى تشاء

jobs:
  indexing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Decode Google Service Account Key
      run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > service-account.json

   - name: Run indexing script
    env:
    SERVICE_ACCOUNT_FILE: service_account.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Run indexing script
      run: python indexing_script.py
